name = "lucky-river-eaf1"
main = "worker.js"
compatibility_date = "2024-09-23"
account_id = "34b1c57751a5a5dd59816ae75362cb69"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "PLAN"
id = "942808b156ae43ef9fb7ca4639672500"

[triggers]
crons = ["0 * * * *", "0 3 * * *"]
